---
title: "Plotly"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(tidyverse)
library(plotly)
```

```{r,include=FALSE}
data(instacart)

instacart_df=instacart[sample(nrow(instacart),200),]
instacart_df
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
y <- list(title = "Days since prior order")
instacart_df %>% 
  mutate(aisle = fct_reorder(aisle,days_since_prior_order)) %>% 
  plot_ly(y = ~days_since_prior_order, color = ~aisle, type = "box", colors = "viridis")%>%
  layout(yaxis=y)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart_df %>% 
  count(aisle) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, type = "bar", colors = "viridis")
```

### Chart C

```{r}
x <- list(title = "Product id")
y <- list(title = "Order hour of day")
instacart_df %>%
  mutate(text_label = str_c("Order hour of day:", order_hour_of_day, "\nProduct id: ", product_id)) %>% 
  plot_ly(
    x = ~product_id, y = ~order_hour_of_day, type = "scatter", mode = "markers", color=~aisle_id,text=~text_label,alpha = 0.5)%>%
  layout(xaxis=x,yaxis=y)
```

